### ISSUE TITLE
Is this ready for general use

### ISSUE THREAD

**Issue by jwaterloo** [ebean-orm/avaje-ebeanorm-typequery#1]
I have been wanting something like this for a while. Is this ready for general use? How do I use it and its agents? Is there a more comprehensive example that includes nested relationship  queries not joins such as the following?
.fetch("current.maintanence.charges", "*", new FetchConfig().query())

**Comment by rbygrave** [comment]
It is ready but I need to:
- provide a maven plugin
- provide an intellij plugin
- do a video to explain a few things

Note that this specifically targets criteria and not the select/fetch
aspect where I am looking to enhance autofetch.

**Comment by rbygrave** [comment]
> .fetch("current.maintanence.charges", "*", new FetchConfig().query())

I'm just adding support for this now so that would instead be written as:

// eagerly fetch all the properties for the path "current.maintanence.charges"
current.maintanence.charges.fetchAll()

Yes, you can also instead of fetchAll() fetch just selected properties.  The documentation should be completed today.

**Comment by rbygrave** [comment]
Documentation now there at  http://ebean-orm.github.io/docs/query-typesafe

I think I'll close this now. 

Note if you are using this in the next day or so you might want to get the updated IntelliJ IDEA plugin version 1.4.1 directly from https://github.com/ebean-orm/typequery-idea-enhancer/blob/master/typequery-idea-enhancer.zip ... as it can take a day or 2 to be moderated and available via the normal channel.
