### ISSUE TITLE
ENH: Add javac annotation processor option for generating the 'query beans'

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-typequery#9]
So this would be an option to use rather than the current generator using main method in src/test etc.

**Comment by icode** [comment]
+1 i like it :+1: :rose:

**Comment by benmccann** [comment]
@rbygrave can you expand a bit more? We have a [PR for adding query bean support to play-ebean](https://github.com/playframework/play-ebean/pull/64), so I'm curious if this is something we could improve upon in the future

**Comment by rbygrave** [comment]
This enhancement is to provide a java annotation processor such that the
type query beans are generated at javac compile time (which is generally a
more standard approach than the current one).

So we would then have 2 options for generating the beans.

I am not sure how well it will integrate with sbt etc (javac oriented).

I might tackle it soon (in the next week) but not sure yet.

Cheers, Rob.

**Comment by rbygrave** [comment]
Note that the current generator can do 3 things:
- generate type query beans
- generate finders
- modify entity beans by adding the finder to them

The javac annotation processor can't modify the entity beans and ideally we
have the option to generate the finders or not.

So there will be functional differences.

**Comment by rbygrave** [comment]
This will be released shortly as "querybean-generator".  Note that will be the preferred option for generating query beans.  

Ultimately this has lead to a discussion on this artifact name "avaje-ebeanorm-typequery" and it now makes sense for this to be renamed to "avaje-ebeanorm-querybean" (and hence related to the querybean-generator etc).
